<?php

namespace TimedBuild;

use pocketmine\plugin\PluginBase;

class Loader extends PluginBase
{
    protected PlayerData $playerData;

    protected function onLoad(): void
    {
        $this->playerData = new PlayerData($this);
    }

    protected function onEnable(): void
    {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    /**
     * @return PlayerData
     */
    public function getPlayerData(): PlayerData
    {
        return $this->playerData;
    }
}